STATE_NAMES = {
  AP: "ANDHRA PRADESH",
  AR: "Arunachal Pradesh",
  AS: "ASSAM",
  BR: "BIHAR",
  CT: "CHHATTISGARH",
  GA: "GOA",
  GJ: "GUJARAT",
  HR: "HARYANA",
  HP: "HIMACHAL PRADESH",
  JH: "JHARKHAND",
  KA: "KARNATAKA",
  KL: "KERALA",
  MP: "MADHYA PRADESH",
  MH: "MAHARASHTRA",
  MN: "MANIPUR",
  ML: "MEGHALAYA",
  MZ: "MIZORAM",
  NL: "NAGALAND",
  OR: "ODISHA",
  PB: "PUNJAB",
  RJ: "RAJASTHAN",
  SK: "SIKKIM",
  TN: "TAMIL NADU",
  TG: "TELANGANA",
  TR: "TRIPURA",
  UT: "UTTARAKHAND",
  UP: "UTTAR PRADESH",
  WB: "WEST BENGAL",
  AN: "ANDAMAN AND NICOBAR ISLANDS",
  CH: "CHANDIGARH",
  DN: "Dadra and Nagar Haveli and Daman and Diu",
  DL: "DELHI",
  JK: "JAMMU AND KASHMIR",
  LA: "LADAKH",
  LD: "Lakshadweep",
  PY: "PUDUCHERRY",
  TT: "India",
};
module.exports.statecodes = STATE_NAMES;
